### ISSUE TITLE
Unable to login to cloud.canister.io with docker login

### ISSUE THREAD

**Issue by zmaslem** [alumae/kaldi-offline-transcriber#19]
docker login is unavailable, getting an error: request canceled (Client.Timeout exceeded while awaiting headers)
Is it going to be available?

**Comment by alumae** [comment]
It was available, but not any more. It seems that my account at canister.io has been terminated. I'm really puzzled about this.

If you know a Docker image repository that allows 10 GB public images, let me know. I cannot push my image to Docker Hub (see https://forums.docker.com/t/unauthorized-authentication-required-when-pushing-a-large-image/57127).

**Comment by alumae** [comment]
Migrated to Google Cloud.
