### ISSUE TITLE
File missing on make

### ISSUE THREAD

**Issue by ngopee** [alumae/kaldi-offline-transcriber#21]
Hi,

I get this error on make .init:

```
utils/prepare_lang.sh: expected --unk-fst build/fst/data/unk_lang_model/unk_fst.txt to exist as a file
Makefile:123: recipe for target 'build/fst/data/prunedlm_unk' failed
make: *** [build/fst/data/prunedlm_unk] Error 1
```

Any idea on what would cause this file to be missing?

**Comment by Saarnaki** [comment]
Have you had any luck with this @ngopee? Having the same issue.

**Comment by ngopee** [comment]
Make sure you have enough ram. I run it on a clean ubuntu machine with more RAM and it works. I'm not sure though if RAM alone was the cause. Might be worth a try.

**Comment by Saarnaki** [comment]
Thanks! Got it to work with 16gb of RAM. Seems like the documented 8gb is not enough.
