### ISSUE TITLE
Estonian acoustic and language models download location

### ISSUE THREAD

**Issue by taunosiitam** [alumae/kaldi-offline-transcriber#24]
README.md tells you to download and unpack the Estonian acoustic and language models from http://bark.phon.ioc.ee/tanel/kaldi-offline-transcriber-data-2018-08-21.tgz

However, that file is no longer there. Where can it be found?

**Comment by alumae** [comment]
Use http://bark.phon.ioc.ee/tanel/kaldi-offline-transcriber-data-2018-09-12.tgz instead.
