### ISSUE TITLE
Makefile:106: recipe for target 'build/fst/data/largelm' failed

### ISSUE THREAD

**Issue by raitraidma** [alumae/kaldi-offline-transcriber#7]
Hello.
I was trying to setup VM by using Vagrant. I managed to pass all previous steps in readme but `make .init` gives an error after running a while:

`HCLGa is not stochastic
add-self-loops --self-loop-scale=0.1 --reorder=true build/fst/nnet2_online_ivector/final.mdl
rm -rf build/fst/data/largelm
mkdir -p build/fst/data/largelm
utils/build_const_arpa_lm.sh \
        language_model/pruned.vestlused-dev.splitw2.arpa.gz build/fst/data/prunedlm build/fst/data/largelm
arpa-to-const-arpa --bos-symbol=199694 --eos-symbol=199695 --unk-symbol=29439 'gunzip -c language_model/pruned.vestlused-dev.splitw2.arpa.gz | utils/map_arpa_lm.pl build/fst/data/largelm/words.txt|' build/fst/data/largelm/G.carpa
utils/map_arpa_lm.pl: Processing "\data\"
utils/map_arpa_lm.pl: Processing "\1-grams:\"
LOG (arpa-to-const-arpa:Read():const-arpa-lm.cc:310) Reading "\data\" section.
LOG (arpa-to-const-arpa:Read():const-arpa-lm.cc:357) Reading "\1-grams:" section.
utils/map_arpa_lm.pl: Processing "\2-grams:\"
LOG (arpa-to-const-arpa:Read():const-arpa-lm.cc:357) Reading "\2-grams:" section.
utils/map_arpa_lm.pl: Processing "\3-grams:\"
LOG (arpa-to-const-arpa:Read():const-arpa-lm.cc:357) Reading "\3-grams:" section.
utils/build_const_arpa_lm.sh: line 48: 18956 Killed                  arpa-to-const-arpa --bos-symbol=$bos --eos-symbol=$eos --unk-symbol=$unk "gunzip -c $arpa_lm | utils/map_arpa_lm.pl $new_lang/words.txt|" $new_lang/G.carpa
Makefile:106: recipe for target 'build/fst/data/largelm' failed
make: *** [build/fst/data/largelm] Error 1`

I don't know much about Makefiles, but to me it seems that when in Makefile recepie `build/fst/data/largelm` is called, it calls `utils/build_const_arpa_lm.sh` but `utils/build_const_arpa_lm.sh` does not get the arguments. (At least variables like $new_lang are not changed)

**Comment by alumae** [comment]
How much RAM do you have available in your VM? It seems to me from the log that the process was killed when `utils/build_const_arpa_lm.sh` was running, and it does require quite a lot of RAM (probably at least 8 GB, maybe more -- I should check and document it).

**Comment by raitraidma** [comment]
The RAM was the problem. Thanks!

**Comment by divyanx** [comment]
How did you resolve it,
I want to run librespeech example script but in run.sh stage 4 its terminating with similar error. Any suggestions what causing the error and how that can be resolved
